### ISSUE TITLE
Reducing a request body stream of Uint8List fails in shelf 1.1.1 or later

### ISSUE THREAD

**Issue by fertrig** [dart-lang/shelf#188]
The test below passes in shelf 1.0.0, but fails in shelf 1.1.1 (or later) with this message:

```
type '(List<int>, List<int>) => List<int>' is not a subtype of type '(Uint8List, Uint8List) => Uint8List' of 'combine'
```

```dart
import 'dart:convert';
import 'dart:typed_data';

import 'package:shelf/shelf.dart';
import 'package:test/test.dart';

void main() {
  group('shelf.Request.read', () {
    test('reduce stream of Uint8List', () async {
      var request = _request(body: genUint8List());
      var bodyBytes = await request.read().reduce((previous, element) {
        return [...previous, ...element];
      });
      expect(bodyBytes, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
    });
  });
}

Request _request({Map<String, String>? headers, body, Encoding? encoding}) {
  return Request('POST', Uri.parse('http://localhost/'),
      headers: headers, body: body, encoding: encoding);
}

Stream<Uint8List> genUint8List() async* {
  for (var i = 0; i <= 9; i++) {
    await Future.microtask(() => null);
    yield Uint8List.fromList([i]);
  }
}
```

My client application is sending json. The server started failing with that error message when I upgraded shelf. This test reproduces the error I am getting in production.

The same test passes when using a stream of `List<int>`. Here is a [gist](https://gist.github.com/fertrig/923103123c1f7d65f699d4a931d14395) showing both scenarios.

**Comment by kevmoo** [comment]
This is...funky.

We used to wrap (`cast`) all of the lists going into the `Request`.  This made sure the runtime time was `List`, but it was horrible for performance.

We fixed that here: https://github.com/dart-lang/shelf/commit/4b9294e29eb308709444a5c0b890fa8ccd69fae4

The result: the **static** return type of `read` is still `Stream<List<int>>`, but the **runtime** type is now `Stream<Uint8List>`.

So `reduce` isn't happy.

The fix:

```dart
      var bodyBytes = await request.read().fold<List<int>>(
        <int>[],
        (previous, element) => previous..addAll(element),
      );
```

You also only allocate **ONE** array, instead of a new one each time around.

**Comment by kevmoo** [comment]
@natebosch likely has better ideas, too 😄
