### ISSUE TITLE
Client disconnection

### ISSUE THREAD

**Issue by loothood** [dart-lang/shelf#300]
Hi,

I'm using shelf_web_socket as a server:
```
void startWebSocketServer() {
    var handler = webSocketHandler((webSocket) {
      webSocket.stream.listen((message) {
        webSocket.sink.add(eventHandler.handle(message));
      });
    });

    serve(handler, url, port).then((server) {
      print('Serving at ws://${server.address.host}:${server.port}');
    });
  }
```
There are up to 10 clients per server. Sometimes client disconnect by application closing. The question is: how to understand what exactly the client disconnected?

**Comment by NotTsunami** [comment]
I presume you've already solved this or moved to another toolset, but in my research on the same problem I came across this issue and want to leave a comment in case anyone else sees this comment. [This](https://stackoverflow.com/questions/55048734/how-does-websocketchannel-warns-that-it-disconnected) StackOverflow question lays it out for us:
> You have to listen on the channel stream and intercept the close event with the onDone callback.

I am hosting both a client (The client connects via `web_socket_channel`) and a server (The server uses `shelf_web_socket`) with Flutter. Following the above Stack Overflow, your original server code becomes:

```
void startWebSocketServer() {
    var handler = webSocketHandler((webSocket) {
      webSocket.stream.listen((message) {
        webSocket.sink.add(eventHandler.handle(message));
      }, onDone: () {
        print('socket closed: reason=[${channel.closeReason}], code:[${channel.closeCode}]');
      });
    });

    serve(handler, url, port).then((server) {
      print('Serving at ws://${server.address.host}:${server.port}');
    });
  }
```

This catches *any* client that disconnects, which is good because that's what we want! If you want to track specific things like a unique client ID or name, you can use `closeReason` for that in `channel.sink.close([int? closeCode, String? closeReason])`. If the target platform is Windows, you can use [window_manager](https://pub.dev/packages/window_manager#confirm-before-closing) (Look at the linked "Confirm before closing" section), or if your target platform is web, you can use [universal_html](https://pub.dev/packages/universal_html). You simply just have to close the stream manually before exiting and send your client ID or identifying information as a string. If I want to do this for a web client, it looks something like:
```
html.window.onBeforeUnload.listen((event) async {
    channel!.sink.close(1000, 'Some important string');
});
```

Note that the 1000 refers to the closeCode, which is defined by [RFC 6455](https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.1).
