### ISSUE TITLE
Invalid argument (requestedUri): handlerPath "/" and url "43" must combine to equal requestedUri path "443".: Instance of '_SimpleUri'

### ISSUE THREAD

**Issue by yixiaco** [dart-lang/shelf#414]
## 1.Specific operations: Set up windows proxy server：

![image](https://github.com/dart-lang/shelf/assets/30982989/34684e80-fb36-4430-ba99-c475d093b717)

## 2.Then create http server
```dart
import 'package:shelf/shelf.dart' as shelf;
import 'package:shelf/shelf_io.dart' as shelf_io;
import 'package:shelf_proxy/shelf_proxy.dart' as proxy;

void main() async {
  var handler = const shelf.Pipeline().addHandler(
        (request) async {
          if(request.requestedUri.host == '127.0.0.1' && request.requestedUri.port == 8080) {
            return shelf.Response.ok('Hello, World!\n');
          }
          return proxy.proxyHandler(request.requestedUri).call(request);
        },
      );

  // Start the server
  var server = await shelf_io.serve(handler, '127.0.0.1', 8080);

  print('Proxy server running at http://127.0.0.1:8080');

}
````

## 3.Use Chrome browser to visit github.com
```dart
flutter: Proxy server running at http://127.0.0.1:8080
ERROR - 2024-02-19 23:41:13.763125
Error parsing request.
Invalid argument (requestedUri): handlerPath "/" and url "43" must combine to equal requestedUri path "443".: Instance of '_SimpleUri'
dart:async  _startMicrotaskLoop
```

I analyzed the source code and found that it was caused by this:
<img width="812" alt="image" src="https://github.com/dart-lang/shelf/assets/30982989/afa4acfc-27ea-4c3f-9e89-0829b97b29bc">

https://github.com/dart-lang/shelf/assets/30982989/f8b74e79-5a62-44b1-91cc-347b20c1a8dd

**Comment by insinfo** [comment]
I'm also seeing this problem, but with webdev 3.4.0 when the internet goes down

**Comment by kevmoo** [comment]
@lrhn – Did you do `_SimpleUri`?

**Comment by lrhn** [comment]
I did, and this is working as intended. 

The _URI_ `google.com:443` has scheme `google.com` and path `443`.
It has no authority part, because an authority part must start with `//`.

The author probably intended to write `Uri.parse('https://google.com:443/')`

**Comment by kevmoo** [comment]
Thanks for clarifying, @lrhn !

**Comment by lrhn** [comment]
That does mean that the shelf `request.dart` file should probably be fixed. Like 352 can be changed to use, fx,  `.pathSegments.join('/')` instead of `substring`, like some other over on the file already does. 
I'd also check if line 340 can be made to pass `-1` as the first argument to `substring`.

**Comment by kevmoo** [comment]
@lrhn – could you clarify a bit more here? I'm not sure I follow. Sounds like we *should* keep this open? Or file a new issue?

**Comment by lrhn** [comment]
The issue here may be using a weird looking URI by accident, but it is a syntactically valid URI. 
The code in this package assumes that a URI of that form cannot occur, which is why it does `.path.substring(1); // Remove leading '/'`.
That assumption is wrong, and the example here shows such a URI reaching that code and removing a leading `4`.

We should either fix the code to not make unwarranted assumptions, or document and enforce that not all URIs are supported valid arguments, so that a URI with a path without a leading `/` won't reach that code.

(Not sure it needs to be this issue, a more directly focused issue is  probably easier to act on.)

**Comment by lrhn** [comment]
`_SimpleUri` has a `toString`, but the error reporting code uses `Error.safeToString` on it to avoid risking more errors while reporting errors.

The issue should only happen for certain "specially-formed" URIs. They're not malformed from the URI syntax perspective, but are maybe not what the author intended. Can you say which URIs you get the issue for? (If you catch the error, you may be able to get to the `Uri` object inside and print its `toString`.)

**Comment by Reprevise** [comment]
Where should I catch the error?

**Comment by lrhn** [comment]
I'll admit I have no idea about the code of Shelf, just `Uri`, so I can't say where an appropriate place to catch errors would be (or if they can be caught at all).

**Comment by kevmoo** [comment]
Not sure if @natebosch or @devoncarew or @brianquinlan is interested in digging into the root cause here at all.
